### ISSUE TITLE
About the checkpoint "fcn_cityscapes_256x512_20201226.pt"

### ISSUE THREAD

**Issue by kennethleng** [Jun-CEN/CMDFusion#3]
Dear author! Thank you very much for your wonderful work. 
When I run the code you provided, I found that the "fcn_cityscapes_256x512_20201226.pt" file is missing. Could you please upload it? Thank you!

**Comment by Jun-CEN** [comment]
Try this one: https://drive.google.com/file/d/1zT-lBElfkD1Sratu4WYiTCRU9PF16lLj/view?usp=sharing

**Comment by kennethleng** [comment]
> 试试这个： https: [//drive.google.com/file/d/1zT-lBElfkD1Sratu4WYiTCRU9PF16lLj/view? usp=sharing](https://drive.google.com/file/d/1zT-lBElfkD1Sratu4WYiTCRU9PF16lLj/view?usp=sharing)
Thank you very much!!
